version: "3.9"

services:
  api:
    volumes:
      - ../apps:/app/apps
      - ../libs:/app/libs
    command: ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  worker:
    volumes:
      - ../apps:/app/apps
      - ../libs:/app/libs
