services:
  api:
    volumes:
      - ../apps:/app/apps
      - ../libs:/app/libs
    working_dir: /app
    environment:
      PYTHONPATH: /app
    command: ["uvicorn", "apps.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    volumes:
      - ../apps:/app/apps
      - ../libs:/app/libs
    working_dir: /app
    environment:
      PYTHONPATH: /app
    command: ["sh","-lc","cd apps/worker && exec celery -A worker.celery_app worker --loglevel=INFO"]
